[package]
name = "day_03"
version = "0.1.0"
authors = ["Daniel Lawrence <danlaw@amazon.com>"]
edition = "2018"

[lib]
name = "day_03"
path = "src/lib.rs"

[dependencies]
regex = "1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
